const wordData = [
  { word: "社团", pinyin: "shetuan", meaning: "club; society" },
  { word: "校园", pinyin: "xiaoyuan", meaning: "campus" },
  { word: "摆", pinyin: "bai", meaning: "to place; to arrange" },
  { word: "摊子", pinyin: "tanzi", meaning: "stall; booth" },
  { word: "社员", pinyin: "sheyuan", meaning: "member (of a club)" },
  { word: "选择", pinyin: "xuanze", meaning: "to choose; choice" },
  { word: "立刻", pinyin: "like", meaning: "immediately; at once" },
  { word: "钢琴", pinyin: "gangqin", meaning: "piano" },
  { word: "功夫", pinyin: "gongfu", meaning: "kung fu; skill" },
  { word: "感兴趣", pinyin: "ganxingqu", meaning: "to be interested in" },
  { word: "艺术", pinyin: "yishu", meaning: "art" },
  { word: "厉害", pinyin: "lihai", meaning: "amazing; formidable" },
  { word: "保护", pinyin: "baohu", meaning: "to protect" },
  { word: "勇敢", pinyin: "yonggan", meaning: "brave; courageous" },
  { word: "吉他", pinyin: "jita", meaning: "guitar" },
  { word: "爱心", pinyin: "aixin", meaning: "love; compassion" },
  { word: "服务", pinyin: "fuwu", meaning: "service" },
  { word: "技巧", pinyin: "jiqiao", meaning: "skill; technique" },
  { word: "複习", pinyin: "fuxi", meaning: "to review; to revise" },
  { word: "地球", pinyin: "diqiu", meaning: "Earth" },
  { word: "互相", pinyin: "huxiang", meaning: "mutually; each other" },
  { word: "恋爱", pinyin: "lianai", meaning: "romantic love; to fall in love" }
];
